"""Relacionamento entre usuario e curso

Revision ID: 36fbebe8b0ea
Revises: b2f6ac03a353
Create Date: 2021-09-10 14:24:40.949037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fbebe8b0ea'
down_revision = 'b2f6ac03a353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('curso', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_usuario_curso_curso'), 'usuario', 'curso', ['curso'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_usuario_curso_curso'), 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'curso')
    # ### end Alembic commands ###
