"""teste 2

Revision ID: 571f59804ce6
Revises: 946a1e413d3b
Create Date: 2021-09-10 15:05:14.027303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571f59804ce6'
down_revision = '946a1e413d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curso', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_turma_curso_curso'), 'curso', ['curso'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_turma_curso_curso'), type_='foreignkey')
        batch_op.drop_column('curso')

    # ### end Alembic commands ###
