"""teste

Revision ID: 946a1e413d3b
Revises: 
Create Date: 2021-09-10 15:04:29.176121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946a1e413d3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curso')),
    sa.UniqueConstraint('nome', name=op.f('uq_curso_nome'))
    )
    op.create_table('qualquer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualquer'))
    )
    op.create_table('turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turma')),
    sa.UniqueConstraint('nome', name=op.f('uq_turma_nome'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=200), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('turma', sa.Integer(), nullable=True),
    sa.Column('curso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.id'], name=op.f('fk_usuario_curso_curso')),
    sa.ForeignKeyConstraint(['turma'], ['turma.id'], name=op.f('fk_usuario_turma_turma')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('nome', name=op.f('uq_usuario_nome'))
    )
    op.create_table('recado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dest', sa.Integer(), nullable=False),
    sa.Column('remetente', sa.String(length=100), nullable=True),
    sa.Column('conteudo', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['dest'], ['usuario.id'], name=op.f('fk_recado_dest_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recado'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recado')
    op.drop_table('usuario')
    op.drop_table('turma')
    op.drop_table('qualquer')
    op.drop_table('curso')
    # ### end Alembic commands ###
