"""Tabela curso adicionada

Revision ID: b2f6ac03a353
Revises: c7ae87a08f69
Create Date: 2021-09-10 14:23:55.089619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f6ac03a353'
down_revision = 'c7ae87a08f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curso')),
    sa.UniqueConstraint('nome', name=op.f('uq_curso_nome'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curso')
    # ### end Alembic commands ###
