"""implementaçao de login

Revision ID: ee691b511d95
Revises: 571f59804ce6
Create Date: 2021-09-16 14:17:58.072378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee691b511d95'
down_revision = '571f59804ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nick', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('senha', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_usuario_nick'), ['nick'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuario_nick'), type_='unique')
        batch_op.drop_column('senha')
        batch_op.drop_column('nick')

    # ### end Alembic commands ###
